site_name: NUS SoC UNIX Workshop
site_url: https://nus-unix-workshop.github.io/2021-s1/
site_author: Ooi Wei Tsang
site_description: "The website for UNIX Workshop"
repo_url: "https://github.com/nus-unix-workshop/2021-s1"
copyright: "This content is licensed under <a href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International</a> license."

theme:
  name: cinder
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - Schedule: schedule.md

markdown_extensions:
  - admonition
  - fontawesome_markdown
  - codehilite:
     linenums: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
